<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';
    $image = 'category_page_grid';
    /** $image = 'new_products_content_widget_grid'; */
    $title = __('New Products'); 
    $items = $block->getProductCollection()->getItems();
	echo $_aloHelper->getGridStyle('.product-items .product-item'); // Config Product Grid

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
/**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
?>
<?php if ($exist):?>
    <div class="container">
    <div class="block widget-none block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified  echo $title; */?></strong>
        </div>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="category-products products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items products <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product-item">' : '</li><li class="item product-item">' ?>
                        <div class="product-item-info" data-container="product-grid category-products-grid">
						    <?php
							$productImage = $block->getImage($_item, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
						    <div class="images-container">
								<div class="product-hover">
									<?php echo $_aloHelper->getLabels($_item); ?>
									<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
										<?php echo $productImage->toHtml(); ?>
									</a>
								</div>
								<div class="actions-no hover-box">
									<div class="product product-item-actions">
										<?php if ($showWishlist || $showCompare || $showCart): ?>
											<div class="actions">
												<?php if ($showWishlist || $showCompare): ?>
													<div class="add-to-links pull-left-none">
														<div class="actions-secondary" data-role="add-to-links">
															<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
																<a href="#"
																   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
																   class="action towishlist link-wishlist" data-action="add-to-wishlist"
																   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
																	<i class="fa fa-heart-o icons"></i><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>
																</a>
															<?php endif; ?>
															<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
																<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
																<a href="#" class="action tocompare"
																   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
																   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
																	<i class="fa fa-signal icons"></i><?php /* @escapeNotVerified */ echo __('Add to Compare') ?>
																</a>
															<?php endif; ?>
															<div class="link-view">
																<button type="button" class="quickview"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_item->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><i class="fa fa-search icons"></i><?php echo __('Quick View')?></span>
																 </button>
															</div>
														</div>
													</div>
												<?php endif; ?>
											</div>
											<?php if ($showCart): ?>
											<div class="actions-primary actions-cart">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary button btn-cart pull-left-none"
																data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php
															$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
															$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary button btn-cart pull-left-none"
																data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									<?php endif; ?>
									</div>
								</div>
							</div>
                            
                            <div class="product details product-item-details products-textlink clearfix">
                               <h2 class="product name product-name product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h2>
								<?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
	</div>
<?php endif;?>
