<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left col-md-6 col-sm-6 col-xs-12">
						<p class="greet welcome-msg"><?php echo $msg; ?></p>
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('call-us')->toHtml();?>
					</div>
					<div class="top-right col-md-6 col-sm-6 col-xs-12">
						<div class="header-setting">
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<div class="text-setting"><?php echo __('My Account'); ?></div>
								</div>
								<div class="dropdown-switcher toggle-content">
									<div class="top-links-alo">
										<div class="header-top-link">
											<?php echo $this->getChildHtml('header.links'); ?>
										</div>
									</div>
								</div>
							</div>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support')->toHtml();?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content header-sticker">
			<div class="container">
				<div class="row">
				    <div class="content-logo col-md-3">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
					<div class="content-cart menu-mobile">
					   <div class="tool-header">
						   <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
							<?php echo $this->getChildHtml('minicart'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom">
			<div class="container">
				<div class="row">
				    <div class="col-sm-3 vertical-menu menu-mobile-none hidden-xs hidden-sm">
				       <?php echo $this->getChildHtml('vmenu'); ?>
				    </div>
				    <div class="content-seach col-md-7 col-sm-5 col-xs-12">
						<div class="search-area header-search">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
				    <div class="col-sm-4 col-md-3 col-lg-2 group-link-main-menu">
				        <?php echo $this->getChildHtml('store_language'); ?>
				    	<?php echo $this->getChildHtml('currency'); ?>
				    </div>
				</div>
			</div>
		</div>
	</div>
</header>
