<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left col-md-7 col-sm-6 col-xs-12">
					    <?php echo $this->getChildHtml('currency'); ?>
						<?php echo $this->getChildHtml('store_language'); ?>
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-bar-social')->toHtml();?>
					</div>
					<div class="top-right col-md-5 col-sm-6 col-xs-12">
						<div class="header-setting">
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<div class="text-setting"><?php echo __('My Account'); ?></div>
								</div>
								<div class="dropdown-switcher toggle-content">
									<div class="top-links-alo">
										<div class="header-top-link">
											<?php echo $this->getChildHtml('header.links'); ?>
										</div>
									</div>
								</div>
							</div>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support')->toHtml();?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container">
				<div class="row">
					<div class="content-seach col-xs-4 col-sm-12 col-md-5 col-lg-4">
						<div class="search-area header-search">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
					<div class="content-logo col-xs-6 col-sm-6 col-md-4 col-lg-4">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="content-cart menu-mobile col-xs-6 col-sm-6 col-md-4 col-lg-4">
					   <div class="tool-header">
							<?php echo $this->getChildHtml('minicart'); ?>
							<a title="My wishlist" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="btn-heart wishlist icon"><?php echo __('Wishlist'); ?></a>
							<a title="Compare" href="<?php echo $this->getUrl('catalog/product_compare') ?>" target="_blank" class="btn-compare icon compare">
							<?php echo __('compare'); ?>
							</a>
							<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom header-sticker">
			<div class="container">
				<div class="row">
				    <div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
