<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-copyright">
	<div class="main">
		<small class="copyright">
			<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
		</small>
		<a href="https://creativewl.com/" target="_blank">Разработка сайта - CreativeWL</a>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>