<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2017-05-27 10:08:29
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> megashop magicproduct +autoplay">
<?php
$tabs = $this->getTabs();
$relatedTabs = $this->getRelatedTabs();
$numTabs = count($tabs);
$isAjax = $this->getAjax();
echo '<h3 class="title">'.$this->getCatName().'</h3>';
if($numTabs): ?>
    <span style="display:none" class="toggle-tab mobile"><i class="fa fa-bars"></i></span>
    <div class="block-title-tabs toggle-content">
		<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
		<?php $activated = $this->getTabActivated();
			$limit = $this->getLimit();
			$single = ($numTabs ==1) ? 'single' : '';
			foreach ($tabs as $type => $name):
				$status  = (!$isAjax || $activated ==$type) ? 'loaded' : '';
				$status .= ($type == $activated) ? " activated $single" : '';
				echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
			endforeach;
		?>
		</ul>
		<div class="floor-elevator">
			<a href="#" class="btn-elevator up fa fa-angle-up"></a>
			<a href="#" class="btn-elevator down fa fa-angle-down"></a>
		</div>
    </div>
<?php endif ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($this->getIdentifier())->toHtml();?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/catalog', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	<div class="product-box clearfix">
	    <div class="row">
		    <div class="col-sm-2 sub-category-wapper">
				<ul class="sub-category-list <?php echo $isAjax ? 'magictabs' : 'magiclinks'?>" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
					 <?php
						foreach ($relatedTabs as $cat):
							echo $isAjax ? '<li class="item cat" data-type ="'.$cat->getEntityId().'"><span class ="title">'.$cat->getName().'</span></li>' : '<li class="item cat" data-type ="'.$cat->getEntityId().'"><a href="'.$cat->getUrl().'"><span class ="title">'.$cat->getName().'</span></a></li>';
						endforeach;
					  ?>
				</ul>
		    </div>
			<div class="col-sm-10 col-right-tab">
				<div class="product-featured clearfix">
					<?php if($image = $this->getImage()): ?>
						<div class="banner-featured">
							<div class="promotion">
								<div class="item">
									<a href="<?php echo $this->getCategory()->getUrl() ?>">
										<div class="scale">
											<img src="<?php echo $this->getMediaUrl() . $image;?>">
										</div>
									</a>
								</div>
							</div>
						</div>
					<?php endif ?>
					<div class="content-products" 
						<?php foreach ($this->getFrontendCfg() as $opt) :?>
							data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
						<?php endforeach;?>        
						>
						<?php 
							$timer = $this->getTimer();
							if($timer) echo $this->getContent('catalog/gridtimer.phtml');	
							else echo $this->getContent('catalog/grid.phtml');	
						?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'magiccart/slick',
		'magicproduct'
		], function($, slick, magicproduct){
			$(".<?php echo $selector?>").magicproduct({
				selector : ".<?php echo $selector?>", // Selector product grid
			});
		});
</script>
