<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2017-05-27 10:07:39
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct magiccategory">
<div class="row">
<?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
if($numTabs): ?>
<div class="col-sm-12 col-md-12 col-lg-4">
	<div class="magic-category">
		<div class="block-title-tabs clearfix">
			<div class="hot-deals-title vertical-text"><h3 class="title"><?php echo __($this->getTitle()); ?></h3></div>
			<div class="hot-deals-tab-box">
				<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
				<?php $activated = $this->getTabActivated();
					$limit = $this->getLimit();
					$single = ($numTabs ==1) ? 'single' : '';
					foreach ($tabs as $type => $name):
						$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
						$status .= ($type == $activated) ? " activated $single" : '';
						echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
					endforeach;
				?>
				</ul>
				<?php 
					$toDate = $this->getCountdown();
					if($toDate){
						$timer = strtotime($toDate) - strtotime("now");
        				echo '<div class="alo-count-down"><span class="countdown" data-timer="' .$timer. '"></span></div>';
					}

				?>
			</div>
		</div>
	</div>
</div>
<?php endif ?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/category', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	<div class="col-sm-12 col-md-12 col-lg-8 hot-deals-tab-content-col">
		<div class="box-product-content clearfix">
			<!--<div class="box-product-adv">
				<div class="promotion">
					<?php //echo __('echo img'); ?>
				</div>
			</div>-->   
			<div class="box-product">
				<div class="content-products" 
				<?php foreach ($this->getFrontendCfg() as $opt) :?>
					data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
				<?php endforeach;?>        
				>
				<?php 
					$timer = $this->getTimer();
					if($timer) echo $this->getContent('category/gridtimer.phtml');	
					else echo $this->getContent('category/grid.phtml');	
				?>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'magiccart/slick',
		'magicproduct'
		], function($, slick, magicproduct){
			$(".<?php echo $selector?>").magicproduct({
				selector : ".<?php echo $selector?>", // Selector product grid
			});
		});
</script>
